export const GET_COORDINATES = 'GET_COORDINATES';
export const GET_MASKDATA = 'GET_MASKDATA';
export const GET_TARGETPOSITION = 'GET_TARGETPOSITION';
export const GET_NOWSELECTDATA = 'GET_NOWSELECTDATA';
